print ("Luis Manuel Lepe")
print("leonardo")
print("Jennifer")
print ("Santoyo")
print("Sofia, otra vez")
print("Holaa:D. Estefania Gutierrez")
print ("Osmar")
print("Daniel Alcaraz)")
print("Edmundo Isaac Gutiérrez Santos")
print ("Juan Pablo Vega")
print ("fernandamejia")
print("Bryan M.")
print ("Diego")
print("Martin")
print("Sarah Atilano")
print("Carlos")